/**
 * Flow Prompt Studio — Format Converter
 *
 * Converts between screenplay formats:
 *   FDX ↔ Fountain ↔ TXT ↔ ScreenJSON
 *
 * Usage:
 *   FormatConverter.convert(inputPath, outputPath, "fountain")
 */

const fs = require("fs");
const path = require("path");
const { ScreenplayParser } = require("./parser");
const { ScreenJSONConverter } = require("./screenjson");

/* ─── Converter ─── */

class FormatConverter {
  /**
   * Convert a screenplay file between formats.
   * Auto-detects input format from extension.
   *
   * @param {string} inputPath — Source file
   * @param {string} outputPath — Destination file
   * @param {string} [toFormat] — Target format (auto-detected from output extension if omitted)
   */
  static convert(inputPath, outputPath, toFormat) {
    const inExt = path.extname(inputPath).toLowerCase();
    const outExt = toFormat || path.extname(outputPath).toLowerCase().replace(".", "");

    // Parse input (any format)
    let parseResult;
    if (inExt === ".fdx" || inExt === ".xml") {
      parseResult = ScreenplayParser.parse(inputPath);
    } else if (inExt === ".screenjson" || inExt === ".json") {
      const json = JSON.parse(fs.readFileSync(inputPath, "utf-8"));
      parseResult = this._screenjsonToParse(json);
    } else {
      // TXT, MD, Fountain, etc.
      parseResult = ScreenplayParser.parse(inputPath);
    }

    // Convert to output format
    switch (outExt) {
      case "fountain":
      case "fountain":
        return this._toFountain(parseResult, outputPath);
      case "fdx":
      case "xml":
        return this._toFdx(parseResult, outputPath);
      case "screenjson":
      case "json":
        return ScreenJSONConverter.toFile(parseResult, outputPath);
      case "txt":
        return this._toTxt(parseResult, outputPath);
      default:
        throw new Error(`Unsupported output format: ${outExt}. Use: fountain, fdx, screenjson, txt`);
    }
  }

  /**
   * List supported format conversions.
   */
  static listFormats() {
    return [
      { ext: ".fountain", name: "Fountain (plain-text screenplay)", desc: "Standard open screenplay format, readable in any text editor" },
      { ext: ".fdx", name: "Final Draft XML", desc: "Industry-standard .fdx format, imports into Final Draft, Fade In, WriterSolo" },
      { ext: ".screenjson", name: "ScreenJSON 1.0", desc: "Open structured JSON format, AI/API-ready, multi-language" },
      { ext: ".txt", name: "Plain Text", desc: "Scene markers + character names, universal compatibility" },
    ];
  }

  /* ─── Output Formats ─── */

  /**
   * Generate Fountain format.
   * Fountain spec: fountain.io
   */
  static _toFountain(parseResult, outputPath) {
    let fountain = "";
    const title = parseResult.stats.filename.replace(/\.[^.]+$/, "");
    fountain += `Title: ${title}\n`;
    fountain += `Credit: Generated by Flow Prompt Studio\n`;
    fountain += `Source: Screenplay analysis\n\n`;

    parseResult.scenes.forEach((scene) => {
      // Scene heading
      fountain += `\n${scene.heading}\n\n`;

      // Scene has characters — add placeholder dialogue markers
      if (scene.characters.length > 0) {
        scene.characters.forEach((char) => {
          fountain += `${char}\n[Character dialogue — ${scene.dialogueCount} lines in this scene]\n\n`;
        });
      } else {
        fountain += `[Scene content — ${scene.dialogueCount} dialogue lines]\n\n`;
      }
    });

    fs.writeFileSync(outputPath, fountain, "utf-8");
    return outputPath;
  }

  /**
   * Generate Final Draft XML (.fdx) format.
   */
  static _toFdx(parseResult, outputPath) {
    let fdx = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    fdx += `<FinalDraft DocumentType="Script" Template="No" Version="5">\n`;
    fdx += `  <Content>\n`;

    parseResult.scenes.forEach((scene) => {
      fdx += `    <Paragraph Type="Scene Heading">\n`;
      fdx += `      <Text>${this._escapeXml(scene.heading)}</Text>\n`;
      fdx += `    </Paragraph>\n`;

      if (scene.characters.length > 0) {
        scene.characters.forEach((char) => {
          fdx += `    <Paragraph Type="Character">\n`;
          fdx += `      <Text>${this._escapeXml(char)}</Text>\n`;
          fdx += `    </Paragraph>\n`;
          fdx += `    <Paragraph Type="Dialogue">\n`;
          fdx += `      <Text>[Dialogue — see original screenplay]</Text>\n`;
          fdx += `    </Paragraph>\n`;
        });
      }
    });

    fdx += `  </Content>\n</FinalDraft>\n`;

    fs.writeFileSync(outputPath, fdx, "utf-8");
    return outputPath;
  }

  /**
   * Generate plain text format.
   */
  static _toTxt(parseResult, outputPath) {
    let txt = `SCREENPLAY ANALYSIS — ${parseResult.stats.filename}\n`;
    txt += `${"=".repeat(50)}\n\n`;
    txt += `Scenes: ${parseResult.stats.totalScenes}\n`;
    txt += `Characters: ${parseResult.stats.totalCharacters}\n`;
    txt += `Dialogue Lines: ${parseResult.stats.totalDialogueLines}\n`;
    txt += `Est. Pages: ${parseResult.stats.estimatedPages}\n`;
    txt += `Est. Duration: ~${parseResult.stats.estimatedDurationMinutes} min\n\n`;
    txt += `${"=".repeat(50)}\n\n`;

    parseResult.scenes.forEach((scene) => {
      txt += `${scene.number}: ${scene.heading}\n`;
      txt += `  Characters: ${scene.characters.join(", ") || "none"}\n`;
      txt += `  Dialogue: ${scene.dialogueCount} lines\n\n`;
    });

    parseResult.characters.forEach((c) => {
      txt += `${c.name}: ${c.count} appearances\n`;
    });

    fs.writeFileSync(outputPath, txt, "utf-8");
    return outputPath;
  }

  /* ─── Reverse: ScreenJSON → Parse Result ─── */

  static _screenjsonToParse(screenjson) {
    const scenes = (screenjson.document?.scenes || []).map((s, i) => ({
      index: i + 1,
      number: `SCENE_${String(i + 1).padStart(2, "0")}`,
      heading: s.heading?.desc?.en || s.heading?.setting || `Scene ${i + 1}`,
      location: s.heading?.setting || "",
      lineNumber: parseInt(s.meta?.lineNumber || "0", 10),
      dialogueCount: parseInt(s.meta?.dialogueCount || "0", 10),
      characters: (s.cast || []).map((id) => {
        const char = (screenjson.characters || []).find((c) => c.id === id);
        return char?.name || id;
      }),
    }));

    const characters = (screenjson.characters || []).map((c) => ({
      name: c.name,
      count: parseInt(c.meta?.appearances || "1", 10),
    }));

    const stats = {
      filename: screenjson.title?.en || "untitled",
      totalLines: 0,
      totalScenes: scenes.length,
      totalCharacters: characters.length,
      totalDialogueLines: 0,
      estimatedPages: Math.ceil(scenes.length * 0.5),
      estimatedDurationMinutes: Math.ceil(scenes.length * 0.5),
    };

    return { scenes, characters, stats };
  }

  static _escapeXml(str) {
    return (str || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
}

module.exports = { FormatConverter };
